[package]
name = "gif-from-screen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eframe.workspace = true
rfd = "0.17.2"
gif-from-screen-application = { path = "../../crates/application" }
gif-from-screen-capture = { path = "../../crates/capture" }
gif-from-screen-capture-linux = { path = "../../crates/capture-linux", features = ["native-wayland", "native-x11"] }
gif-from-screen-domain = { path = "../../crates/domain" }
gif-from-screen-editor = { path = "../../crates/editor" }
gif-from-screen-gif = { path = "../../crates/gif" }
gif-from-screen-localization = { path = "../../crates/localization" }
gif-from-screen-media = { path = "../../crates/media" }
gif-from-screen-project = { path = "../../crates/project" }
gif-from-screen-render = { path = "../../crates/render" }
gif-from-screen-text = { path = "../../crates/text" }
gif-from-screen-workflow = { path = "../../crates/workflow" }
thiserror.workspace = true
uuid.workspace = true
wgpu.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
fs2 = "0.4.3"
rustix = { version = "1", features = ["fs", "process"] }

[dev-dependencies]
ttf-parser = "0.25.1"
sha2 = "0.10.9"

[lints]
workspace = true
