//! Bounded snapshots of already authored frame-owned overlays.
//!
//! Legacy time-anchored tracks are deliberately excluded: copying those would
//! change the existing clipboard/Yoyo contract. No pixel file or recorded
//! input is read, interpreted, or regenerated by this module.

use std::{
    collections::{BTreeMap, BTreeSet},
    io::{self, Write},
};

use gif_from_screen_domain::{
    AssetId, FrameId, MAX_ANNOTATION_SCOPE_SPANS, MAX_FRAME_OVERLAY_CELLS, MAX_FRAME_OVERLAY_MARKS,
    OverlayId, OverlayTrack, ProjectManifest, TrackId,
};
use thiserror::Error;

/// Maximum serialized selected-cell and necessary track metadata before cloning.
pub const MAX_FRAME_BUNDLE_METADATA_BYTES: usize = 16 * 1024 * 1024;
/// Maximum frame-owned groups in one bounded snapshot.
pub const MAX_FRAME_BUNDLE_TRACKS: usize = 4_096;
const MAX_ID_ATTEMPTS: usize = 64;
const MAX_OCCUPIED_IDENTITIES: usize = 1_000_000;

/// Frozen frame-owned groups accompanying copied clips, without pixel bytes.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct FrameBundle {
    tracks: Vec<OverlayTrack>,
}

/// Failure while extracting, validating, or remapping copied authored marks.
#[derive(Clone, Debug, Error, Eq, PartialEq)]
pub enum FrameBundleError {
    /// One bounded metadata collection would be too large.
    #[error("frame annotation bundle exceeds its {kind} budget")]
    Budget {
        /// Collection whose limit was exceeded.
        kind: &'static str,
    },
    /// The source selection referred to a nonexistent frame.
    #[error("frame annotation bundle references missing frame {frame_id}")]
    UnknownFrame {
        /// Missing source identity.
        frame_id: FrameId,
    },
    /// A copied cell has no supplied target-frame identity.
    #[error("frame annotation bundle has no destination identity for frame {frame_id}")]
    MissingFrameMapping {
        /// Unmapped source identity.
        frame_id: FrameId,
    },
    /// A destination identity was nil or assigned to multiple source frames.
    #[error("frame annotation bundle requires distinct nonzero destination frame identities")]
    InvalidFrameMapping,
    /// A source track mixed frame-owned data with legacy time anchors.
    #[error("frame-owned source track contains incompatible timed items or scope")]
    InvalidRepresentation,
    /// The injected identity factory repeatedly returned nil or occupied IDs.
    #[error(
        "could not allocate a distinct nonzero {kind} identity after {MAX_ID_ATTEMPTS} attempts"
    )]
    IdentityExhausted {
        /// Identity namespace that could not be allocated.
        kind: &'static str,
    },
    /// A frozen mark cannot be persisted using the destination's asset registry.
    #[error("frame annotation asset {asset_id} is not registered in the destination")]
    MissingAsset {
        /// Required immutable raster identity.
        asset_id: AssetId,
    },
}

impl FrameBundle {
    /// Copies selected cells and their complete recipes/styles, including
    /// hidden marks and unmarked authoring scope. Frames can disappear from
    /// the source after this snapshot is returned.
    ///
    /// # Errors
    /// Rejects unknown frame identities and excessive metadata/count budgets
    /// before cloning a source track. Pixel assets are never read.
    pub fn capture(
        project: &ProjectManifest,
        selected: &BTreeSet<FrameId>,
    ) -> Result<Self, FrameBundleError> {
        let known: BTreeSet<_> = project
            .timeline
            .frames
            .iter()
            .map(|frame| frame.id)
            .collect();
        if let Some(frame_id) = selected.iter().find(|id| !known.contains(id)) {
            return Err(FrameBundleError::UnknownFrame {
                frame_id: *frame_id,
            });
        }
        let full_selection = !selected.is_empty() && selected.len() == known.len();
        let mut tracks = Vec::new();
        let mut budget = BundleBudget::default();
        for track in &project.timeline.overlay_tracks {
            let Some(cells) = &track.frame_cells else {
                continue;
            };
            if !(cells.iter().any(|cell| selected.contains(&cell.frame_id))
                || full_selection && cells.is_empty())
            {
                continue;
            }
            if !track.items.is_empty() || track.annotation_scope.is_some() {
                return Err(FrameBundleError::InvalidRepresentation);
            }
            // Unselected cells neither consume the copy budget nor get cloned.
            budget.include(track, selected)?;
            tracks.push(OverlayTrack {
                id: track.id,
                frame_cells: Some(
                    cells
                        .iter()
                        .filter(|cell| selected.contains(&cell.frame_id))
                        .cloned()
                        .collect(),
                ),
                annotation: track.annotation.clone(),
                annotation_scope: None,
                name: track.name.clone(),
                visible: track.visible,
                opacity: track.opacity,
                blend_mode: track.blend_mode,
                items: Vec::new(),
            });
        }
        Ok(Self { tracks })
    }

    /// Source identities and frozen recipes/styles in original track order.
    pub fn tracks(&self) -> &[OverlayTrack] {
        &self.tracks
    }

    /// Every referenced raster, including hidden and zero-opacity marks.
    pub fn referenced_assets(&self) -> impl Iterator<Item = AssetId> + '_ {
        self.tracks.iter().flat_map(OverlayTrack::referenced_assets)
    }

    /// Checks metadata references without loading pixel bytes.
    ///
    /// # Errors
    /// Returns the first asset missing from the destination registry.
    pub fn validate_assets(&self, project: &ProjectManifest) -> Result<(), FrameBundleError> {
        for asset_id in self.referenced_assets() {
            if !project.assets.contains_key(&asset_id) {
                return Err(FrameBundleError::MissingAsset { asset_id });
            }
        }
        Ok(())
    }

    /// Clones the frozen cells using supplied frame identities. New tracks
    /// isolate authoring run IDs and future edits from their source group.
    ///
    /// # Errors
    /// Rejects missing/invalid mappings and an exhausted injected identity
    /// source. The snapshot and destination remain unchanged on failure.
    pub fn remap<G>(
        &self,
        frame_ids: &BTreeMap<FrameId, FrameId>,
        identities: &mut FrameBundleIdentities,
        generate: &mut G,
    ) -> Result<Vec<OverlayTrack>, FrameBundleError>
    where
        G: FnMut() -> FrameId,
    {
        let mut destinations = BTreeSet::new();
        if frame_ids
            .values()
            .any(|id| id.is_nil() || !destinations.insert(*id))
        {
            return Err(FrameBundleError::InvalidFrameMapping);
        }
        let mut output = Vec::with_capacity(self.tracks.len());
        for source in &self.tracks {
            let mut track = source.clone();
            track.id = identities.track(generate)?;
            for cell in track
                .frame_cells
                .as_mut()
                .ok_or(FrameBundleError::InvalidRepresentation)?
            {
                cell.frame_id = *frame_ids.get(&cell.frame_id).ok_or(
                    FrameBundleError::MissingFrameMapping {
                        frame_id: cell.frame_id,
                    },
                )?;
                for mark in &mut cell.marks {
                    mark.id = identities.mark(generate)?;
                }
            }
            output.push(track);
        }
        Ok(output)
    }
}

/// Shared namespaces for an entire paste/import, including legacy tracks.
pub struct FrameBundleIdentities {
    tracks: BTreeSet<TrackId>,
    marks: BTreeSet<OverlayId>,
}

impl FrameBundleIdentities {
    /// Seeds both namespaces from source and destination groups, including
    /// invisible marks. Repeated identities are deduplicated.
    ///
    /// # Errors
    /// Rejects more than one million occupied identities in either namespace.
    pub fn new<'a>(
        tracks: impl IntoIterator<Item = &'a OverlayTrack>,
    ) -> Result<Self, FrameBundleError> {
        let mut result = Self {
            tracks: BTreeSet::new(),
            marks: BTreeSet::new(),
        };
        for track in tracks {
            result.tracks.insert(track.id);
            if result.tracks.len() > MAX_OCCUPIED_IDENTITIES {
                return Err(FrameBundleError::Budget {
                    kind: "occupied track identities",
                });
            }
            for (id, _) in track.all_mark_contents() {
                result.marks.insert(id);
                if result.marks.len() > MAX_OCCUPIED_IDENTITIES {
                    return Err(FrameBundleError::Budget {
                        kind: "occupied mark identities",
                    });
                }
            }
        }
        Ok(result)
    }

    /// Allocates and reserves a track identity using the shared entropy source.
    ///
    /// # Errors
    /// Rejects a factory that cannot produce a free nonzero ID within 64 calls.
    pub fn track<G: FnMut() -> FrameId>(
        &mut self,
        generate: &mut G,
    ) -> Result<TrackId, FrameBundleError> {
        fresh_identity(
            &mut self.tracks,
            generate,
            TrackId::from_bytes,
            TrackId::is_nil,
            "track",
        )
    }

    /// Allocates and reserves an overlay identity using the shared entropy source.
    ///
    /// # Errors
    /// Rejects a factory that cannot produce a free nonzero ID within 64 calls.
    pub fn mark<G: FnMut() -> FrameId>(
        &mut self,
        generate: &mut G,
    ) -> Result<OverlayId, FrameBundleError> {
        fresh_identity(
            &mut self.marks,
            generate,
            OverlayId::from_bytes,
            OverlayId::is_nil,
            "overlay",
        )
    }
}

fn fresh_identity<I: Ord + Copy, G: FnMut() -> FrameId>(
    occupied: &mut BTreeSet<I>,
    generate: &mut G,
    wrap: impl Fn([u8; 16]) -> I,
    is_nil: impl Fn(I) -> bool,
    kind: &'static str,
) -> Result<I, FrameBundleError> {
    // Existing editing APIs inject 128-bit entropy through FrameId factories.
    // Wrap that same entropy by namespace here, never reinterpret IDs at call
    // sites. Source, destination, and this operation's IDs share each set.
    for _ in 0..MAX_ID_ATTEMPTS {
        let id = wrap(*generate().as_bytes());
        if !is_nil(id) && occupied.insert(id) {
            return Ok(id);
        }
    }
    Err(FrameBundleError::IdentityExhausted { kind })
}

#[derive(Default)]
struct BundleBudget {
    tracks: usize,
    cells: usize,
    scopes: usize,
    marks: usize,
    bytes: MetadataCounter,
}

impl BundleBudget {
    fn include(
        &mut self,
        track: &OverlayTrack,
        selected: &BTreeSet<FrameId>,
    ) -> Result<(), FrameBundleError> {
        add(&mut self.tracks, 1, MAX_FRAME_BUNDLE_TRACKS, "tracks")?;
        serde_json::to_writer(
            &mut self.bytes,
            &(
                track.id,
                &track.annotation,
                &track.name,
                track.visible,
                track.opacity,
                track.blend_mode,
            ),
        )
        .map_err(|_| FrameBundleError::Budget {
            kind: "serialized metadata bytes",
        })?;
        for cell in track
            .frame_cells
            .iter()
            .flatten()
            .filter(|cell| selected.contains(&cell.frame_id))
        {
            add(&mut self.cells, 1, MAX_FRAME_OVERLAY_CELLS, "cells")?;
            add(
                &mut self.scopes,
                cell.scopes.len(),
                MAX_ANNOTATION_SCOPE_SPANS,
                "scope fragments",
            )?;
            add(
                &mut self.marks,
                cell.marks.len(),
                MAX_FRAME_OVERLAY_MARKS,
                "marks",
            )?;
            serde_json::to_writer(&mut self.bytes, cell).map_err(|_| FrameBundleError::Budget {
                kind: "serialized metadata bytes",
            })?;
        }
        Ok(())
    }
}

fn add(
    total: &mut usize,
    count: usize,
    maximum: usize,
    kind: &'static str,
) -> Result<(), FrameBundleError> {
    *total = total
        .checked_add(count)
        .filter(|sum| *sum <= maximum)
        .ok_or(FrameBundleError::Budget { kind })?;
    Ok(())
}

#[derive(Default)]
struct MetadataCounter(usize);

impl Write for MetadataCounter {
    fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        self.0 = self
            .0
            .checked_add(bytes.len())
            .filter(|total| *total <= MAX_FRAME_BUNDLE_METADATA_BYTES)
            .ok_or_else(|| io::Error::other("frame bundle metadata budget exceeded"))?;
        Ok(bytes.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

#[cfg(test)]
#[path = "frame_bundle_tests.rs"]
mod tests;
